"""phase 2 coupons reviews wishlist returns

Revision ID: 199899183cc0
Revises: b5ff915a5fcc
Create Date: 2026-09-22 05:22:08.867836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199899183cc0'
down_revision: Union[str, Sequence[str], None] = 'b5ff915a5fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('percent', 'fixed', name='couponkind', native_enum=False, length=20), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('amount_off_cents', sa.Integer(), nullable=True),
    sa.Column('min_subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'percent' AND percent_off BETWEEN 1 AND 100 AND amount_off_cents IS NULL) OR (kind = 'fixed' AND amount_off_cents >= 1 AND percent_off IS NULL)", name=op.f('ck_coupons_amount_matches_kind')),
    sa.CheckConstraint('max_redemptions IS NULL OR max_redemptions >= 1', name=op.f('ck_coupons_max_redemptions_positive')),
    sa.CheckConstraint('min_subtotal_cents >= 0', name=op.f('ck_coupons_min_subtotal_non_negative')),
    sa.CheckConstraint('per_user_limit >= 1', name=op.f('ck_coupons_per_user_limit_positive')),
    sa.CheckConstraint('starts_at IS NULL OR expires_at IS NULL OR starts_at < expires_at', name=op.f('ck_coupons_window_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name=op.f('uq_coupons_code'))
    )
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_redemptions_coupon_id_coupons')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_redemptions_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_redemptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_redemptions')),
    sa.UniqueConstraint('order_id', name=op.f('uq_coupon_redemptions_order_id'))
    )
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'cancelled', 'received', name='returnstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reason', sa.Enum('damaged', 'wrong_item', 'not_as_described', 'no_longer_needed', 'other', name='returnreason', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('staff_note', sa.String(length=500), nullable=True),
    sa.Column('restocked', sa.Boolean(), nullable=True),
    sa.Column('refund_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'received') = (refund_cents IS NOT NULL)", name=op.f('ck_returns_refund_iff_received')),
    sa.CheckConstraint('refund_cents IS NULL OR refund_cents >= 0', name=op.f('ck_returns_refund_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_returns_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_returns_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_returns')),
    sa.UniqueConstraint('return_number', name=op.f('uq_returns_return_number'))
    )
    op.create_index(op.f('ix_returns_order_id'), 'returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_returns_user_id'), 'returns', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reviews_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('product_id', 'user_id', name='uq_reviews_product_user')
    )
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_wishlist_items_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlist_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist_items')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_wishlist_user_product')
    )
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_return_items_quantity_positive')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_return_items_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], name=op.f('fk_return_items_return_id_returns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_items')),
    sa.UniqueConstraint('return_id', 'order_item_id', name='uq_return_items_line')
    )
    op.create_index(op.f('ix_return_items_return_id'), 'return_items', ['return_id'], unique=False)
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('rating_total', sa.Integer(), server_default='0', nullable=False))
    # REV-03: seeded ratings become a star total, so reviews can add to them exactly.
    op.execute("UPDATE products SET rating_total = ROUND(rating_avg * rating_count) WHERE rating_count > 0")
    op.create_check_constraint(
        op.f('ck_products_rating_total_range'),
        'products',
        'rating_total BETWEEN rating_count AND 5 * rating_count',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_products_rating_total_range'), 'products', type_='check')
    op.drop_column('products', 'rating_total')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'delivered_at')
    op.drop_index(op.f('ix_return_items_return_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_returns_user_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_order_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_coupon_redemptions_user_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_table('coupons')
    # ### end Alembic commands ###
