"""order idempotency and expiry index

Revision ID: b5ff915a5fcc
Revises: a646495bbdbc
Create Date: 2026-09-21 19:23:27.484019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ff915a5fcc'
down_revision: Union[str, Sequence[str], None] = 'a646495bbdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=64), nullable=False))
    op.add_column('orders', sa.Column('request_hash', sa.String(length=64), nullable=False))
    op.create_index('ix_orders_status_payment_expires_at', 'orders', ['status', 'payment_expires_at'], unique=False)
    op.create_unique_constraint('uq_orders_user_idempotency_key', 'orders', ['user_id', 'idempotency_key'])
    op.add_column('payments', sa.Column('request_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'request_hash')
    op.drop_constraint('uq_orders_user_idempotency_key', 'orders', type_='unique')
    op.drop_index('ix_orders_status_payment_expires_at', table_name='orders')
    op.drop_column('orders', 'request_hash')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
