"""Deterministic seed data. Tests rely on these exact values - change them deliberately.

Some products are intentionally placed on business-rule boundaries:
  * stock 0 / 1 / 5 / 6          -> CAT-05 "Out of stock" / "Only X left" thresholds
  * price $49.99 / $50.00        -> CHK-03 free-shipping threshold
  * archived product             -> ADM-01 hidden from storefront
"""

from decimal import Decimal

SEED_PASSWORDS = {
    "admin@homebasics.test": "Admin12345",
    "customer@homebasics.test": "Customer123",
    "shopper2@homebasics.test": "Shopper123",
}

USERS = [
    {"email": "admin@homebasics.test", "first_name": "Ada", "last_name": "Admin", "role": "admin"},
    {
        "email": "customer@homebasics.test",
        "first_name": "Casey",
        "last_name": "Customer",
        "role": "customer",
    },
    {
        "email": "shopper2@homebasics.test",
        "first_name": "Sam",
        "last_name": "Shopper",
        "role": "customer",
    },
]

CATEGORIES = [
    ("Kitchen", "kitchen", "Cookware, utensils and food storage for everyday cooking."),
    ("Cleaning", "cleaning", "Sprays, sponges, mops and everything to keep the house spotless."),
    ("Bath", "bath", "Towels, bath mats, shower accessories and toiletries."),
    ("Laundry", "laundry", "Detergents, hampers, drying racks and ironing gear."),
    ("Storage", "storage", "Bins, baskets, hangers and organizers for every room."),
    ("Paper Goods", "paper-goods", "Paper towels, toilet paper, tissues and napkins."),
]

# (category_slug, sku, name, price_cents, stock_qty, description)
PRODUCTS = [
    # Kitchen
    (
        "kitchen",
        "KIT-001",
        "Nonstick Frying Pan 10in",
        2499,
        40,
        "PFOA-free nonstick pan with a stay-cool handle.",
    ),
    (
        "kitchen",
        "KIT-002",
        "Stainless Steel Mixing Bowls (Set of 3)",
        1999,
        35,
        "Nesting bowls with non-slip bases.",
    ),
    (
        "kitchen",
        "KIT-003",
        "Silicone Spatula Set",
        1299,
        60,
        "Heat-resistant to 450F, dishwasher safe.",
    ),
    (
        "kitchen",
        "KIT-004",
        "Glass Food Storage Containers (10 pc)",
        3499,
        25,
        "Oven-safe glass with snap-lock lids.",
    ),
    (
        "kitchen",
        "KIT-005",
        "Bamboo Cutting Board",
        1599,
        5,
        "Large reversible board with juice groove.",
    ),
    ("kitchen", "KIT-006", "Chef's Knife 8in", 4999, 18, "High-carbon stainless steel blade."),
    ("kitchen", "KIT-007", "Electric Kettle 1.7L", 5000, 12, "Rapid boil with automatic shut-off."),
    (
        "kitchen",
        "KIT-008",
        "Measuring Cups and Spoons Set",
        999,
        80,
        "Stainless steel, engraved markings.",
    ),
    (
        "kitchen",
        "KIT-009",
        "Dish Drying Rack",
        2799,
        0,
        "Two-tier rack with utensil holder and drip tray.",
    ),
    (
        "kitchen",
        "KIT-010",
        "Reusable Silicone Food Bags (4 pk)",
        1499,
        45,
        "Leak-proof, freezer and microwave safe.",
    ),
    # Cleaning
    (
        "cleaning",
        "CLN-001",
        "All-Purpose Cleaner Spray 32oz",
        499,
        150,
        "Cuts grease on counters, sinks and appliances.",
    ),
    (
        "cleaning",
        "CLN-002",
        "Microfiber Cleaning Cloths (12 pk)",
        1299,
        90,
        "Lint-free and machine washable.",
    ),
    (
        "cleaning",
        "CLN-003",
        "Spin Mop and Bucket System",
        3999,
        15,
        "Foot-pedal spin wringer with 2 refills.",
    ),
    (
        "cleaning",
        "CLN-004",
        "Non-Scratch Scrub Sponges (6 pk)",
        599,
        120,
        "Safe on nonstick and glass.",
    ),
    (
        "cleaning",
        "CLN-005",
        "Glass Cleaner 26oz",
        399,
        1,
        "Streak-free shine for windows and mirrors.",
    ),
    (
        "cleaning",
        "CLN-006",
        "Toilet Bowl Cleaner (2 pk)",
        699,
        70,
        "Clinging gel with angled nozzle.",
    ),
    (
        "cleaning",
        "CLN-007",
        "Cordless Handheld Vacuum",
        5999,
        9,
        "Rechargeable with washable filter.",
    ),
    (
        "cleaning",
        "CLN-008",
        "Rubber Cleaning Gloves (3 pairs)",
        799,
        6,
        "Latex-free, cotton-lined.",
    ),
    ("cleaning", "CLN-009", "Broom and Dustpan Set", 1999, 30, "Upright dustpan with comb teeth."),
    (
        "cleaning",
        "CLN-010",
        "Disinfecting Wipes (3 x 75 ct)",
        1149,
        100,
        "Kills 99.9% of household germs.",
    ),
    # Bath
    ("bath", "BTH-001", "Cotton Bath Towel Set (6 pc)", 4499, 20, "600 GSM ring-spun cotton."),
    ("bath", "BTH-002", "Memory Foam Bath Mat", 1899, 40, "Non-slip backing, quick dry."),
    (
        "bath",
        "BTH-003",
        "Fabric Shower Curtain with Liner",
        2299,
        25,
        "Water-repellent, includes 12 hooks.",
    ),
    (
        "bath",
        "BTH-004",
        "Toothbrush Holder",
        899,
        55,
        "Ceramic with 4 slots and a toothpaste slot.",
    ),
    (
        "bath",
        "BTH-005",
        "Shower Caddy Stainless",
        2599,
        3,
        "Rust-proof hanging caddy with 3 shelves.",
    ),
    (
        "bath",
        "BTH-006",
        "Liquid Hand Soap Refill 50oz",
        849,
        65,
        "Moisturizing formula, fresh scent.",
    ),
    ("bath", "BTH-007", "Toilet Plunger with Holder", 1199, 33, "Heavy-duty with drip tray caddy."),
    ("bath", "BTH-008", "Hand Towels (4 pk)", 1699, 0, "Soft cotton in neutral grey."),
    ("bath", "BTH-009", "Bathroom Scale Digital", 2499, 14, "Measures to 400 lb with LCD display."),
    ("bath", "BTH-010", "Cotton Swabs (500 ct)", 349, 110, "Paper stems, 100% cotton tips."),
    # Laundry
    ("laundry", "LND-001", "Liquid Laundry Detergent 100oz", 1399, 80, "HE compatible, 64 loads."),
    ("laundry", "LND-002", "Collapsible Laundry Hamper", 1799, 42, "Divided hamper with handles."),
    ("laundry", "LND-003", "Wool Dryer Balls (6 pk)", 1499, 50, "Reduce drying time, reusable."),
    ("laundry", "LND-004", "Folding Drying Rack", 3299, 16, "Holds up to 32 lb, folds flat."),
    ("laundry", "LND-005", "Ironing Board with Cover", 4299, 8, "Adjustable height, cotton cover."),
    (
        "laundry",
        "LND-006",
        "Stain Remover Spray 22oz",
        599,
        95,
        "Pretreats grease, grass and wine.",
    ),
    (
        "laundry",
        "LND-007",
        "Fabric Softener Sheets (240 ct)",
        999,
        4,
        "Reduces static and wrinkles.",
    ),
    (
        "laundry",
        "LND-008",
        "Velvet Hangers (50 pk)",
        2999,
        22,
        "Non-slip, space-saving slim profile.",
    ),
    ("laundry", "LND-009", "Mesh Laundry Bags (5 pk)", 899, 60, "Protects delicates in the wash."),
    ("laundry", "LND-010", "Steam Iron 1700W", 3999, 11, "Vertical steam and auto shut-off."),
    # Storage
    (
        "storage",
        "STR-001",
        "Clear Storage Bins with Lids (6 pk)",
        3999,
        28,
        "Stackable 15 qt bins.",
    ),
    (
        "storage",
        "STR-002",
        "Woven Storage Baskets (3 pk)",
        2799,
        19,
        "Seagrass baskets with handles.",
    ),
    (
        "storage",
        "STR-003",
        "Under-Bed Storage Bags (2 pk)",
        1999,
        37,
        "Zippered with clear window.",
    ),
    ("storage", "STR-004", "Over-the-Door Organizer", 1599, 44, "24 pockets for shoes or pantry."),
    (
        "storage",
        "STR-005",
        "Drawer Organizer Trays (8 pc)",
        1299,
        2,
        "Mix-and-match sizes, non-slip pads.",
    ),
    ("storage", "STR-006", "Vacuum Storage Bags (10 pk)", 2499, 26, "Hand pump included."),
    ("storage", "STR-007", "Stackable Shoe Rack", 3499, 13, "3 tiers, holds 12 pairs."),
    ("storage", "STR-008", "Label Maker", 4999, 7, "Handheld with QWERTY keyboard."),
    (
        "storage",
        "STR-009",
        "Lazy Susan Turntable",
        1199,
        48,
        "11in non-skid turntable for cabinets.",
    ),
    ("storage", "STR-010", "Garage Wall Hooks (10 pk)", 2199, 0, "Heavy-duty steel utility hooks."),
    # Paper Goods
    (
        "paper-goods",
        "PPR-001",
        "Paper Towels (12 Double Rolls)",
        2399,
        75,
        "Strong and absorbent select-a-size.",
    ),
    ("paper-goods", "PPR-002", "Toilet Paper (24 Mega Rolls)", 2899, 60, "2-ply, septic safe."),
    (
        "paper-goods",
        "PPR-003",
        "Facial Tissues (8 boxes)",
        1199,
        85,
        "Soft 2-ply, 120 sheets per box.",
    ),
    ("paper-goods", "PPR-004", "Paper Napkins (500 ct)", 799, 90, "Everyday 1-ply napkins."),
    ("paper-goods", "PPR-005", "Paper Plates 9in (100 ct)", 1099, 5, "Soak-proof, microwave safe."),
    ("paper-goods", "PPR-006", "Aluminum Foil 200 sq ft", 899, 55, "Heavy-duty non-stick foil."),
    ("paper-goods", "PPR-007", "Plastic Wrap 400 sq ft", 599, 66, "Cling wrap with slide cutter."),
    (
        "paper-goods",
        "PPR-008",
        "Parchment Paper Sheets (200 ct)",
        1399,
        31,
        "Pre-cut unbleached sheets.",
    ),
    ("paper-goods", "PPR-009", "Trash Bags 13 gal (120 ct)", 1899, 70, "Drawstring, odor control."),
    ("paper-goods", "PPR-010", "Sandwich Bags (300 ct)", 699, 1, "Zip-close, BPA-free."),
]

# ADM-01: archived - must never appear on the storefront.
ARCHIVED_PRODUCTS = [
    ("kitchen", "KIT-900", "Discontinued Toaster", 2999, 10, "No longer sold."),
]

# CHK-02 simplified flat rates. TX is 8.25% per the BRD. Not tax advice.
TAX_RATES: list[tuple[str, str, Decimal]] = [
    ("AL", "Alabama", Decimal("0.04")),
    ("AK", "Alaska", Decimal("0")),
    ("AZ", "Arizona", Decimal("0.056")),
    ("AR", "Arkansas", Decimal("0.065")),
    ("CA", "California", Decimal("0.0725")),
    ("CO", "Colorado", Decimal("0.029")),
    ("CT", "Connecticut", Decimal("0.0635")),
    ("DE", "Delaware", Decimal("0")),
    ("DC", "District of Columbia", Decimal("0.06")),
    ("FL", "Florida", Decimal("0.06")),
    ("GA", "Georgia", Decimal("0.04")),
    ("HI", "Hawaii", Decimal("0.04")),
    ("ID", "Idaho", Decimal("0.06")),
    ("IL", "Illinois", Decimal("0.0625")),
    ("IN", "Indiana", Decimal("0.07")),
    ("IA", "Iowa", Decimal("0.06")),
    ("KS", "Kansas", Decimal("0.065")),
    ("KY", "Kentucky", Decimal("0.06")),
    ("LA", "Louisiana", Decimal("0.05")),
    ("ME", "Maine", Decimal("0.055")),
    ("MD", "Maryland", Decimal("0.06")),
    ("MA", "Massachusetts", Decimal("0.0625")),
    ("MI", "Michigan", Decimal("0.06")),
    ("MN", "Minnesota", Decimal("0.06875")),
    ("MS", "Mississippi", Decimal("0.07")),
    ("MO", "Missouri", Decimal("0.04225")),
    ("MT", "Montana", Decimal("0")),
    ("NE", "Nebraska", Decimal("0.055")),
    ("NV", "Nevada", Decimal("0.0685")),
    ("NH", "New Hampshire", Decimal("0")),
    ("NJ", "New Jersey", Decimal("0.06625")),
    ("NM", "New Mexico", Decimal("0.04875")),
    ("NY", "New York", Decimal("0.04")),
    ("NC", "North Carolina", Decimal("0.0475")),
    ("ND", "North Dakota", Decimal("0.05")),
    ("OH", "Ohio", Decimal("0.0575")),
    ("OK", "Oklahoma", Decimal("0.045")),
    ("OR", "Oregon", Decimal("0")),
    ("PA", "Pennsylvania", Decimal("0.06")),
    ("RI", "Rhode Island", Decimal("0.07")),
    ("SC", "South Carolina", Decimal("0.06")),
    ("SD", "South Dakota", Decimal("0.042")),
    ("TN", "Tennessee", Decimal("0.07")),
    ("TX", "Texas", Decimal("0.0825")),
    ("UT", "Utah", Decimal("0.061")),
    ("VT", "Vermont", Decimal("0.06")),
    ("VA", "Virginia", Decimal("0.053")),
    ("WA", "Washington", Decimal("0.065")),
    ("WV", "West Virginia", Decimal("0.06")),
    ("WI", "Wisconsin", Decimal("0.05")),
    ("WY", "Wyoming", Decimal("0.04")),
]
